# Generated by Django 2.2.5 on 2019-09-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
        ('blog_app', '0002_auto_20190916_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='author_app.Author'),
        ),
    ]
