# Generated by Django 2.2.5 on 2019-09-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogs_author_id'),
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog_app.Blogs'),
        ),
    ]
